#This is config for reading from file app

title = "Config to reading app"

[file]
#path is empty if file is in the same directory
path = ""
#the name of files should be listed below. Each file name should goes inside " and be spereted by comma.
names = [
	"f1.bin",
	"f2.bin"
]

[settings]
#speed of reading. Value in Kbyte/sec
#speed shoud be equal to "-1.0" to read without limitation
speed = 25.0